services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "3200:80"
    env_file:
      - .env
    volumes:
      - ./src/emails.csv:/app/src/emails.csv
      - ./src/bindings.json:/app/src/bindings.json
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
