services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "3200:80"
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
